config/routes.rb
Rails.application.routes.draw do

  resources :label_types
  resources :product_images
  resources :labels
  resources :posts, except: [:new, :edit]
  resources :product_variants
  resources :products

  get 'all' => 'welcome#index'
  root 'welcome#index'

  get '*unmatched_route', to: 'application#raise_not_found'
end

app/controllers/label_types_controller.rb
class LabelTypesController < ApplicationController
  before_action :set_label_type, only: [:show, :edit, :update, :destroy]

  # GET /label_types
  def index
    @label_types = LabelType.all
  end

  # GET /label_types/1
  def show
  end

  # GET /label_types/new
  def new
    @label_type = LabelType.new
  end

  # GET /label_types/1/edit
  def edit
  end

  # POST /label_types
  def create
    @label_type = LabelType.new(label_type_params)

    if @label_type.save
      redirect_to @label_type, notice: 'Label type was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /label_types/1
  def update
    if @label_type.update(label_type_params)
      redirect_to @label_type, notice: 'Label type was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /label_types/1
  def destroy
    @label_type.destroy
    redirect_to label_types_url, notice: 'Label type was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_label_type
      @label_type = LabelType.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def label_type_params
      params.require(:label_type).permit(:name, :label_id)
    end
end

app/helpers/label_types_helper.rb
module LabelTypesHelper
end

app/views/label_types/_form.html.erb
<%= form_for(label_type) do |f| %>
  <% if label_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(label_type.errors.count, "error") %> prohibited this label_type from being saved:</h2>

      <ul>
      <% label_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :label_id %>
    <%= f.text_field :label_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/label_types/edit.html.erb
<h1>Editing Label Type</h1>

<%= render 'form', label_type: @label_type %>

<%= link_to 'Show', @label_type %> |
<%= link_to 'Back', label_types_path %>

app/views/label_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Label Types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Label</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @label_types.each do |label_type| %>
      <tr>
        <td><%= label_type.name %></td>
        <td><%= label_type.label %></td>
        <td><%= link_to 'Show', label_type %></td>
        <td><%= link_to 'Edit', edit_label_type_path(label_type) %></td>
        <td><%= link_to 'Destroy', label_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Label Type', new_label_type_path %>

app/views/label_types/new.html.erb
<h1>New Label Type</h1>

<%= render 'form', label_type: @label_type %>

<%= link_to 'Back', label_types_path %>

app/views/label_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @label_type.name %>
</p>

<p>
  <strong>Label:</strong>
  <%= @label_type.label %>
</p>

<%= link_to 'Edit', edit_label_type_path(@label_type) %> |
<%= link_to 'Back', label_types_path %>